version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./main.go:/app/main.go
      - ./index.html:/app/index.html
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/assets/vendor/nextgen-form/credentials.json